title: gpioblink (じぶりん)
description: フロント、サーバーサイド問わずいろいろやってきました。最近は、低レイヤにはまり、組込Linuxの設計やリバースエンジニアリングも行なっています。
logo: https://github.com/gpioblink.png
github:
  owner_url: rirekisho.pdf
theme: jekyll-theme-minimal